---
version: "2.1"
services:
#duplicati
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIGFOLDER}/duplicati/config:/config
      - ${BACKUPFOLDER}:/backups
      - ${SOURCEFOLDER}:/source
    ports:
      - 8200:8200
    restart: unless-stopped
