---
version: "2.1"
services:
#nginx proxy manager
  nginxproxymanager:
    image: jlesage/nginx-proxy-manager
    container_name: nginx-proxy-manager
    ports:
      - 80:80 #http traffic
      - 81:81 #dashboard location
      - 443:443 #https traffic
    volumes:
      - ${CONFIGFOLDER}/nginx-proxy-manager:/config:rw
    restart: unless-stopped
