---
version: "2.1"
services:
#tautulli
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIGFOLDER}/tautulli:/config
      - ${CONFIGFOLDER}/plexmediaserver/Library/Application Support/Plex Media Server/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
