---
version: "2.1"
services:
  varken:
    hostname: varken
    container_name: varken
    image: boerderij/varken
    networks:
      - skynet
    volumes:
      - ${CONFIGFOLDER}/varken:/config
    environment:
      - DATA_FOLDER=/config
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
      - VRKN_GLOBAL_MAXMIND_LICENSE_KEY=${MAXMINDAPI}
      - VRKN_LIDARR_1_APIKEY=${LIDARRKEY}
      - VRKN_RADARR_1_APIKEY=${RADARRKEY}
      - VRKN_SONARR_1_APIKEY=${SONARRKEY}
      - VRKN_TAUTULLI_1_APIKEY=${TAUTULIKEY}
      - VRKN_INFLUXDB_USERNAME=varken
      - VRKN_INFLUXDB_URL={SERVERIP}
      - VRKN_LIDARR_1_URL={SERVERIP}:8686
      - VRKN_RADARR_1_URL={SERVERIP}:7878
      - VRKN_SONARR_1_URL={SERVERIP}:8989
      - VRKN_TAUTULLI_1_URL={SERVERIP}:8181
      - VRKN_GLOBAL_LIDARR_SERVER_IDS=1
      - VRKN_GLOBAL_RADARR_SERVER_IDS=1
      - VRKN_GLOBAL_SONARR_SERVER_IDS=1
      - VRKN_GLOBAL_TAUTULLI_SERVER_IDS=1
      - VRKN_INFLUXDB_PORT=8086
      - VRKN_INFLUXDB_SSL=false
      - VRKN_INFLUXDB_VERIFY_SSL=false
      - VRKN_LIDARR_1_FUTURE_DAYS=30
      - VRKN_LIDARR_1_FUTURE_DAYS_RUN_SECONDS=300
      - VRKN_LIDARR_1_MISSING_DAYS=30
      - VRKN_LIDARR_1_MISSING_DAYS_RUN_SECONDS=300
      - VRKN_LIDARR_1_QUEUE=true
      - VRKN_LIDARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_LIDARR_1_SSL=false
      - VRKN_LIDARR_1_VERIFY_SSL=false
      - VRKN_RADARR_1_GET_MISSING=true
      - VRKN_RADARR_1_GET_MISSING_RUN_SECONDS=300
      - VRKN_RADARR_1_QUEUE=true
      - VRKN_RADARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_RADARR_1_SSL=false
      - VRKN_RADARR_1_VERIFY_SSL=false
      - VRKN_SONARR_1_FUTURE_DAYS=1
      - VRKN_SONARR_1_FUTURE_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_1_MISSING_DAYS=7
      - VRKN_SONARR_1_MISSING_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_1_QUEUE=true
      - VRKN_SONARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_SONARR_1_SSL=false
      - VRKN_SONARR_1_VERIFY_SSL=false,
      - VRKN_TAUTULLI_1_FALLBACK_IP=1.1.1.1
      - VRKN_TAUTULLI_1_GET_ACTIVITY=true
      - VRKN_TAUTULLI_1_GET_ACTIVITY_RUN_SECONDS=30
      - VRKN_TAUTULLI_1_GET_STATS=true
      - VRKN_TAUTULLI_1_GET_STATS_RUN_SECONDS=3600
      - VRKN_TAUTULLI_1_SSL=false
      - VRKN_TAUTULLI_1_VERIFY_SSL=false
    depends_on:
        - influxdb
    restart: unless-stopped
networks:
  skynet:
    external: true
