version: "2.1"
services:
#plex
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - VERSION=docker
      - PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config/Library/Application Support
      - DEBIAN_FRONTEND=noninteractive
      - PLEX_DOWNLOAD=https://downloads.plex.tv/plex-media-server-new
    volumes:
      - ${CONFIGFOLDER}/plexmediaserver:/config
      - ${TVFOLDER}:/media/tv
      - ${MOVIEFOLDER}:/media/movies
      - ${MUSICFOLDER}:/media/music
      - ${PHOTOSFOLDER}:/media/photos
    restart: unless-stopped
