---
version: "2.1"
services:
#pihole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8070:80/tcp
      - 9443:443/tcp
    environment:
      - TZ=${TIMEZONE}
      - WEBPASSWORD=${MYPASSWORD}
    volumes:
      - ${CONFIGFOLDER}/pihole/config/etc-pihole/:/etc/pihole/
      - ${CONFIGFOLDER}/pihole/config/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
